name: Handle Noop Webserver Releases

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-and-publish:
    name: Build and Publish New Versions of Noop Webserver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Noop Discovery Repo
        uses: actions/checkout@v2
      - name: Publish to NPM
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Update NPM Version
        run: npm i -g npm@latest
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}